using System.Text.RegularExpressions;
using AwesomeAssertions;
using Emlang.CodeGen;
using Xunit;

namespace Emlang.CodeGen.Tests;

/// <summary>
/// The skeleton emitter's gate (ADR 018): per game, the emitted text carries exactly one
/// switch arm AND one private static partial declaration per spec e:/c: — so a new spec
/// element lands as a CS8795 seam, never a silently missing arm.
/// </summary>
public class DeciderEmitterTests
{
    private static void EmitsOneArmAndOnePartialPerSpecElement(GameManifest manifest)
    {
        var spec = File.ReadAllText(Path.Combine(RepoRoot.Locate(), manifest.SpecPath));
        var elements = SpecModel.Parse(spec);

        var text = DeciderEmitter.Emit(manifest, elements);

        text.Should().StartWith("// <auto-generated/>");
        text.Should().Contain($"namespace {manifest.Namespace};");
        text.Should().Contain("public static partial class Decider");
        text.Should().NotContain("_ =>", "exhaustive union switches have no default arm");

        foreach (var e in elements.Where(x => x.Kind == 'e'))
        {
            Regex.Matches(text, Regex.Escape($"{e.Name} e => Evolve{e.Name}(state, e),")).Should().HaveCount(1);
            Regex.Matches(text, Regex.Escape(
                $"private static partial {manifest.StateType} Evolve{e.Name}({manifest.StateType} state, {e.Name} e);"))
                .Should().HaveCount(1);
        }

        foreach (var c in elements.Where(x => x.Kind == 'c'))
        {
            Regex.Matches(text, Regex.Escape($"{c.Name} c => Decide{c.Name}(state, c, context),")).Should().HaveCount(1);
            Regex.Matches(text, Regex.Escape(
                $"private static partial Result<{manifest.EventUnion}[]> Decide{c.Name}({manifest.StateType} state, {c.Name} command, {manifest.ContextType} context);"))
                .Should().HaveCount(1);
        }
    }

    [Fact]
    public void MerEllerMindre_skeleton_has_one_arm_and_one_partial_per_spec_element() =>
        EmitsOneArmAndOnePartialPerSpecElement(GameManifest.MerEllerMindre);

    [Fact]
    public void Blindbudet_skeleton_has_one_arm_and_one_partial_per_spec_element() =>
        EmitsOneArmAndOnePartialPerSpecElement(GameManifest.Blindbudet);

    [Fact]
    public void TankTillTusen_skeleton_has_one_arm_and_one_partial_per_spec_element() =>
        EmitsOneArmAndOnePartialPerSpecElement(GameManifest.TankTillTusen);
}
