using AwesomeAssertions;
using Emlang.CodeGen;
using Xunit;

namespace Emlang.CodeGen.Tests;

/// <summary>
/// The emitter's correctness proof: feed the emitted text back through the step-0
/// SurfaceComparer against the REAL spec — zero divergences means the generated
/// surface is exactly what the shadow harness verified the committed files to be.
/// </summary>
public class SurfaceEmitterTests
{
    private static void EmittedSurfaceRoundTrips(GameManifest manifest)
    {
        var spec = File.ReadAllText(Path.Combine(RepoRoot.Locate(), manifest.SpecPath));
        var elements = SpecModel.Parse(spec);

        SurfaceComparer.Compare(manifest, spec,
                SurfaceEmitter.Emit(manifest, elements, 'c'),
                SurfaceEmitter.Emit(manifest, elements, 'e'),
                SurfaceEmitter.Emit(manifest, elements, 'x'))
            .Should().BeEmpty("the emitted surface must match the spec it was emitted from");
    }

    [Fact]
    public void MerEllerMindre_emitted_surface_round_trips_through_the_comparer() =>
        EmittedSurfaceRoundTrips(GameManifest.MerEllerMindre);

    [Fact]
    public void Blindbudet_emitted_surface_round_trips_through_the_comparer() =>
        EmittedSurfaceRoundTrips(GameManifest.Blindbudet);

    [Fact]
    public void TankTillTusen_emitted_surface_round_trips_through_the_comparer() =>
        EmittedSurfaceRoundTrips(GameManifest.TankTillTusen);

    [Fact]
    public void Blindbudet_commands_emit_known_records_and_the_closed_union()
    {
        var spec = File.ReadAllText(Path.Combine(RepoRoot.Locate(), GameManifest.Blindbudet.SpecPath));

        var text = SurfaceEmitter.Emit(GameManifest.Blindbudet, SpecModel.Parse(spec), 'c');

        text.Should().StartWith("// <auto-generated/>");
        text.Should().Contain("namespace Blindbudet.Domain;");
        text.Should().Contain("public record PlaceBid(Guid GameId, Guid PlayerId, int LotIndex, decimal Amount);");
        text.Should().Contain("public union AuctionCommand(");
    }

    [Fact]
    public void Errors_emit_parameterless_marker_records()
    {
        var spec = File.ReadAllText(Path.Combine(RepoRoot.Locate(), GameManifest.Blindbudet.SpecPath));

        var text = SurfaceEmitter.Emit(GameManifest.Blindbudet, SpecModel.Parse(spec), 'x');

        text.Should().Contain("public record AuctionNotFound;");
        text.Should().Contain("public union AuctionError(");
    }
}
